config/routes.rb
Rails.application.routes.draw do
  
  resources :parkings, :except => [:new]
  get '/map', to: 'parkings#map', as: :map
  get '/json', to: 'parkings#json', as: :json
  get '/output', to: 'parkings#output', as: :output
  root :to => "parkings#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/parking.rb
class Parking < ApplicationRecord

	mount_uploader :main_picture, MainPictureUploader

	validates :lat, numericality: {greater_than_or_equal_to: -90, less_than_or_equal_to: 90}
	validates :lng, numericality: {greater_than_or_equal_to: -180, less_than_or_equal_to: 180}
	validates :name, presence: true
	validates :address, presence: true
	validates :slug, presence: true
	validates :has_watchman, inclusion: [true, false]
	validates :zip_code, presence: true, format: {:with => /\A\d{5}\z/, :message => 'only five numbers' }
	validates :district, presence: true, format: {:with => /\A\d{1,2}\z/, :message => 'only one or two number(s)' }
	validates :city, presence: true
	validates :price_month, numericality: {greater_than: 0}
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  	
  	protect_from_forgery with: :exception
	
end

app/controllers/parkings_controller.rb
require "json"
require "open-uri"
class ParkingsController < ApplicationController
  before_action :set_parking, only: [:show, :edit, :update, :destroy]

  # GET /parkings
  # GET /parkings.json
  def index
    @parkings = Parking.find_by_sql ["Select address, 
                                             available, 
                                             name,
                                             has_camera,
                                             has_watchman,
                                             city,
                                             main_picture,
                                             price_month,
                                             zip_code,
                                             district,
                                             id FROM parkings"]
    @parking = Parking.new
  end

  # GET /parkings/1
  # GET /parkings/1.json
  def show
  end

  # GET /parkings/new
  def new
    @parking = Parking.new
  end

  # GET /parkings/1/edit
  def edit
  end

  # POST /parkings
  # POST /parkings.json
  def create
    @parking = Parking.new(parking_params)
    latLng = latLng(@parking.address, @parking.city)
    @parking.district = district(@parking.zip_code, @parking.city)
    @parking.lat = latLng[0]
    @parking.lng = latLng[1]
    @parking.slug = @parking.name.parameterize
    respond_to do |format|
      if @parking.save
        format.html { redirect_to parkings_path notice: 'Parking was successfully created.' }
        format.json { render :show, status: :created, location: @parking }
      else
        format.html { render :new }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parkings/1
  # PATCH/PUT /parkings/1.json
  def update
    latLng = latLng(@parking.address, @parking.city)
    respond_to do |format|
      if @parking.update(parking_params)
        @parking.update(:lat => latLng[0], 
                        :slug => @parking.name.parameterize,
                        :lng => latLng[1], 
                        :district => district(@parking.zip_code, @parking.city))
        format.html { redirect_to parkings_path, notice: 'Parking was successfully updated.' }
        format.json { render :show, status: :ok, location: @parking }
      else
        format.html { render :edit }
        format.json { render json: @parking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parkings/1
  # DELETE /parkings/1.json
  def destroy
    @parking.destroy
    respond_to do |format|
      format.html { redirect_to parkings_url, notice: 'Parking was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def map
    @parkings = Parking.find_by_sql ["Select lat, 
                                             lng, 
                                             name FROM parkings"]
    gon.parkings = @parkings
  end

  def json
    root = Rails.root.to_s
    file = File.read("#{root}/parkings_input.json")
      parkings = JSON.parse(file)
      parkings.each do |parking|
        latLng = latLng(parking["address"], parking["city"])
        newParking = Parking.new(:slug => parking["name"].parameterize, 
                     :district => district(parking["zip_code"], parking["city"]), 
                     :lat => latLng[0],
                     :lng => latLng[1], 
                     :name => parking["name"], 
                     :address => parking["address"], 
                     :city => parking["city"], 
                     :zip_code => parking["zip_code"], 
                     :price_month => parking["price_month"],
                     :main_picture => parking["main_picture"], 
                     :has_watchman => parking["has_watchman"], 
                     :has_camera => parking["has_camera"], 
                     :available => parking["available"])
        newParking.remote_main_picture_url = parking["main_picture"]
        newParking.save
      end
      respond_to do |format|
        format.html { redirect_to parkings_url, notice: 'parkings_imput has been imported.' }
        format.json { head :no_content }
      end
  end

  def output
    @parkings = Parking.all
    parkings = []
    @parkings.each do |parking|
      parkings.push({:id => parking.id, 
       :lat => parking.lat,
       :lng => parking.lng,
       :name => parking.name,
       :address => parking.address,
       :available => parking.available,
       :slug => parking.slug,
       :updated_at => parking.updated_at,
       :has_camera => parking.has_camera,
       :has_watchman => parking.has_watchman,
       :zip_code => parking.zip_code,
       :district => parking.district,
       :city => parking.city,
       :main_picture => parking.main_picture,
       :price_month => parking.price_month})
    end
    File.open("output.json","w"){|f| f.write(JSON.pretty_generate(parkings))}
    respond_to do |format|
      format.html { redirect_to parkings_url, notice: 'output.json has been created.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parking
      parking = Parking.find_by_sql ["Select address,
                                             id, 
                                             available, 
                                             name,
                                             has_camera,
                                             has_watchman,
                                             city,
                                             main_picture,
                                             price_month,
                                             zip_code
                                             FROM parkings
                                             WHERE id = ?", params[:id]]
      @parking = parking.first
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parking_params
      params.require(:parking).permit(:address, :available, :has_camera, :has_watchman, :city, :main_picture, :price_month, :zip_code, :lng, :slug, :district, :name, :lat)
    end

    def latLng (address, city)
      geo = Geokit::Geocoders::GoogleGeocoder.geocode "#{address}" + ', ' + "#{city}"
      latLong = geo.ll.split(',')
    end

    def district (zip_code, city)
      district = if city == "Paris"
        zip_code.last(2)
      else
        "0"
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Yespark</title>
	<%= include_gon %>
	<%= stylesheet_link_tag    'application', media: 'all' %>
	<%= javascript_include_tag 'application' %>
	<%= csrf_meta_tags %>
</head>

<body>
	<div class="row">
		<nav class="navbar navbar-inverse navbar-fixed-top">
			<div class="container-fluid">
				<div class="navbar-header">
					<a class="navbar-brand">Yespark Test</a>
				</div>
				<ul class="nav navbar-nav">
					<li><%= link_to 'Index', parkings_path %></li>
					<li><%= link_to 'Map', map_path %></li>
					<li><%= link_to 'Import Json', json_path %></li>
					<li><%= link_to 'create output.json', output_path %></li>
				</ul>
			</div>
		</nav>
		<div class="col-md-6 col-md-offset-3">
			<%= yield %>
		</div>
	</div>
</body>
</html>

app/views/parkings/_form.html.erb
<% modal ||= false %>
<% remote = modal ? true : false %>
<%= form_for @parking, remote: remote, html: {role: :form, 'data-model' => 'parking'}, authenticity_token: true do |f| %>
  <% if @parking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@parking.errors.count, "error") %> prohibited this parking from being saved:</h2>

      <ul>
      <% @parking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :address, class: 'control-label' %><br>
    <%= f.text_field :address, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :available, class: 'control-label' %><br>
    <%= f.check_box :available, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :has_camera, class: 'control-label' %><br>
    <%= f.check_box :has_camera, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :has_watchman, class: 'control-label' %><br>
    <%= f.check_box :has_watchman, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :city, class: 'control-label' %><br>
    <%= f.text_field :city, class: 'form-control' %>
  </div>

  <div class="form-group">
      <%= f.label :main_picture, class: 'control-label' %><br>
      <%= f.file_field :main_picture, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :price_month, class: 'control-label' %><br>
    <%= f.number_field :price_month, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :zip_code, class: 'control-label' %><br>
    <%= f.text_field :zip_code, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :name, class: 'control-label' %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= f.submit 'Submit', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/parkings/edit.html.erb
<h1>Editing Parking</h1>

<%= render 'form', parking: @parking %>

<%= link_to 'Show', @parking %> |
<%= link_to 'Back', parkings_path %>

app/views/parkings/index.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'New Parking', '#new_parking', 'data-toggle' => 'modal' %><br>

<h1>Parkings</h1>

<table class="table table-striped" id="parkings">
  <thead>
    <tr>
      <th>Address</th>
      <th>Available</th>
      <th>Has camera</th>
      <th>Has watchman</th>
      <th>City</th>
      <th>Main picture</th>
      <th>Price month</th>
      <th>Zip code</th>
      <th>District</th>
      <th>Name</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @parkings.each do |parking| %>
      <tr>
        <td><%= parking.address %></td>
        <td><% if parking.available == true %><div class="available">
          <% else %><div class="false"></div>
          <% end %></td>
        <td><% if parking.has_camera == true %><div class="camera">
          <% else %><div class="false"></div>
          <% end %></td>
        <td><% if parking.has_watchman == true %><div class="watchman">
          <% else %><div class="false"></div>
          <% end %></td>
        <td><%= parking.city %></td>
        <td><%= image_tag parking.main_picture.url(:thumb) %></td>
        <td><%= parking.price_month %></td>
        <td><%= parking.zip_code %></td>
        <td><%= parking.district %></td>
        <td><%= parking.name %></td>
        <td><%= link_to 'Show parking', parking %>
          <%= link_to 'Edit parking', edit_parking_path(parking) %>
          <%= link_to 'Delete parking', parking, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="modal fade" id="new_parking" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">New parking</h4>
      </div>
      <div class="modal-body">
        <%= render 'form', modal: true %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/parkings/map.html.erb
<h1>Parkings's map</h1>

<div id="map" style="width:100%;height:700px"></div>


<script>
    function initMap() {
    	var myLatLng = {lat: 48.856614, lng: 2.352222};

// Create a map object and specify the DOM element for display.
        var map = new google.maps.Map(document.getElementById('map'), {
          center: myLatLng,
          scrollwheel: false,
          zoom: 10
        });

        var parkings = gon.parkings;
        parkings.forEach(markers)

// Create a marker and set its position.
        function markers(parking){
        	var latLng = {lat: parking.lat, lng: parking.lng};
        	var marker = new google.maps.Marker({
          map: map,
          position: latLng,
          title: parking.name
          });
        }      
    }
</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBrQNcdHy_BEaTs3aJRvIGHXnEdLTEjDKs&callback=initMap"
async defer></script>

app/views/parkings/new.html.erb
<h1>New Parking</h1>

<%= render 'form', parking: @parking %>

<%= link_to 'Back', parkings_path %>

app/views/parkings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @parking.address %>
</p>

<p>
  <strong>Available:</strong>
  <%= @parking.available %>
</p>

<p>
  <strong>Has camera:</strong>
  <%= @parking.has_camera %>
</p>

<p>
  <strong>Has watchman:</strong>
  <%= @parking.has_watchman %>
</p>

<p>
  <strong>City:</strong>
  <%= @parking.city %>
</p>

<p>
  <strong>Main picture:</strong>
  <%= image_tag @parking.main_picture.url(:thumb) %>
</p>

<p>
  <strong>Price month:</strong>
  <%= @parking.price_month %>
</p>

<p>
  <strong>Zip code:</strong>
  <%= @parking.zip_code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @parking.name %>
</p>

<%= link_to 'Edit parking', edit_parking_path(@parking) %> |
<%= link_to 'Back to parkings', parkings_path %>